name: RRO CI
permissions:
  contents: write
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Create signing key
      run: echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release_key.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run : |
          ./gradlew assembleRelease
          mkdir -p apk_out
          cp sysui/build/outputs/apk/release/sysui-release.apk apk_out/MxGSystemUIOverlayHelper.apk
          cp framework/build/outputs/apk/release/framework-release.apk apk_out/MxGFrameworkOverlayHelper.apk
          cp chargebottle/build/outputs/apk/release/chargebottle-release.apk apk_out/MxGBottleAnimationOverlayHelper.apk
          cp chargeglow/build/outputs/apk/release/chargeglow-release.apk apk_out/MxGGlowAnimationOverlayHelper.apk
          cp chargeparticle/build/outputs/apk/release/chargeparticle-release.apk apk_out/MxGParticleAnimationOverlayHelper.apk

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: overlay-artifacts
        path: apk_out/

    - name: Commit and Push APKs
      env:
        EMAIL: ${{ secrets.NOREPLY_EMAIL }}
      run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$EMAIL"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add apk_out
          git commit -m "[CI] Upload built APKs"
          git push
